# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod Properties
mod_name=VanillaDisable
mod_id=vanilla_disable
mod_author=DragonEggBedrockBreaking
mod_version=3.3.3
mod_description=Allows you to disable a lot of vanilla features.
maven_group=uk.debb
license=MPL-2.0
credits=Wesley1808, FallenBreath, NoComment, LittleLily, ThatTrollzer, Kichura, ellieisjelly

# Common
minecraft_version=1.20.6
h2_version=2.2.224
parchment_mc_version=1.20.6
parchment_version=2024.06.02
mixin_extras_version=0.3.6
fabric_mixin_version=0.13.4+mixin.0.8.5
enabled_platforms=fabric,neoforge

# Fabric
fabric_loader_version=0.15.11
modmenu_version=10.0.0-beta.1

# NeoForge
neoforge_version=20.6.109-beta
neoforge_loader_version_range=(1,)
minecraft_version_range=(1.20.4, 1.21)
h2_version_range=[2.2.224, 2.3)
