accessWidener v2 named

accessible class net/minecraft/world/entity/animal/Bee$BeeAttackGoal
accessible class net/minecraft/world/entity/animal/Bee$BaseBeeGoal
accessible class net/minecraft/world/entity/animal/Bee$BeeEnterHiveGoal
accessible class net/minecraft/world/entity/animal/Bee$BeeWanderGoal
accessible class net/minecraft/world/entity/animal/Bee$BeeGrowCropGoal
accessible class net/minecraft/world/entity/animal/Bee$BeeHurtByOtherGoal
accessible class net/minecraft/world/entity/animal/Bee$BeeLocateHiveGoal
accessible class net/minecraft/world/entity/animal/Bee$BeePollinateGoal
accessible class net/minecraft/world/entity/monster/Blaze$BlazeAttackGoal
accessible class net/minecraft/world/entity/animal/Cat$CatTemptGoal
accessible class net/minecraft/world/entity/animal/Dolphin$DolphinSwimToTreasureGoal
accessible class net/minecraft/world/entity/animal/Dolphin$DolphinSwimWithPlayerGoal
accessible class net/minecraft/world/entity/animal/Dolphin$PlayWithItemsGoal
accessible class net/minecraft/world/entity/animal/Cat$CatRelaxOnOwnerGoal
accessible class net/minecraft/world/entity/monster/Drowned$DrownedAttackGoal
accessible class net/minecraft/world/entity/monster/Drowned$DrownedSwimUpGoal
accessible class net/minecraft/world/entity/monster/Drowned$DrownedGoToBeachGoal
accessible class net/minecraft/world/entity/monster/Drowned$DrownedGoToWaterGoal
accessible class net/minecraft/world/entity/monster/Drowned$DrownedTridentAttackGoal
accessible class net/minecraft/world/entity/monster/EnderMan$EndermanFreezeWhenLookedAt
accessible class net/minecraft/world/entity/monster/EnderMan$EndermanLeaveBlockGoal
accessible class net/minecraft/world/entity/monster/EnderMan$EndermanTakeBlockGoal
accessible class net/minecraft/world/entity/animal/AbstractFish$FishSwimGoal
accessible class net/minecraft/world/entity/animal/Fox$FaceplantGoal
accessible class net/minecraft/world/entity/animal/Fox$FoxBehaviorGoal
accessible class net/minecraft/world/entity/animal/Fox$FoxBreedGoal
accessible class net/minecraft/world/entity/animal/Fox$FoxLookAtPlayerGoal
accessible class net/minecraft/world/entity/animal/Fox$FoxMeleeAttackGoal
accessible class net/minecraft/world/entity/animal/Fox$FoxPanicGoal
accessible class net/minecraft/world/entity/animal/Fox$FoxSearchForItemsGoal
accessible class net/minecraft/world/entity/animal/Fox$FoxStrollThroughVillageGoal
accessible class net/minecraft/world/entity/animal/Fox$StalkPreyGoal
accessible class net/minecraft/world/entity/animal/Fox$PerchAndSearchGoal
accessible class net/minecraft/world/entity/animal/Fox$SeekShelterGoal
accessible class net/minecraft/world/entity/animal/Fox$SleepGoal
accessible class net/minecraft/world/entity/monster/Ghast$GhastLookGoal
accessible class net/minecraft/world/entity/monster/Ghast$GhastShootFireballGoal
accessible class net/minecraft/world/entity/monster/Ghast$RandomFloatAroundGoal
accessible class net/minecraft/world/entity/monster/Guardian$GuardianAttackGoal
accessible class net/minecraft/world/entity/animal/horse/Llama$LlamaAttackWolfGoal
accessible class net/minecraft/world/entity/animal/horse/Llama$LlamaHurtByTargetGoal
accessible class net/minecraft/world/entity/animal/horse/TraderLlama$TraderLlamaDefendWanderingTraderGoal
accessible class net/minecraft/world/entity/animal/Ocelot$OcelotTemptGoal
accessible class net/minecraft/world/entity/animal/Panda$PandaAttackGoal
accessible class net/minecraft/world/entity/animal/Panda$PandaBreedGoal
accessible class net/minecraft/world/entity/animal/Panda$PandaHurtByTargetGoal
accessible class net/minecraft/world/entity/animal/Panda$PandaLieOnBackGoal
accessible class net/minecraft/world/entity/animal/Panda$PandaLookAtPlayerGoal
accessible class net/minecraft/world/entity/animal/Panda$PandaPanicGoal
accessible class net/minecraft/world/entity/animal/Panda$PandaRollGoal
accessible class net/minecraft/world/entity/animal/Panda$PandaSitGoal
accessible class net/minecraft/world/entity/animal/Panda$PandaSneezeGoal
accessible class net/minecraft/world/entity/animal/Parrot$ParrotWanderGoal
accessible class net/minecraft/world/entity/monster/Phantom$PhantomAttackPlayerTargetGoal
accessible class net/minecraft/world/entity/monster/Phantom$PhantomAttackStrategyGoal
accessible class net/minecraft/world/entity/monster/Phantom$PhantomMoveTargetGoal
accessible class net/minecraft/world/entity/animal/PolarBear$PolarBearAttackPlayersGoal
accessible class net/minecraft/world/entity/animal/PolarBear$PolarBearHurtByTargetGoal
accessible class net/minecraft/world/entity/animal/PolarBear$PolarBearMeleeAttackGoal
accessible class net/minecraft/world/entity/animal/PolarBear$PolarBearPanicGoal
accessible class net/minecraft/world/entity/animal/Pufferfish$PufferfishPuffGoal
accessible class net/minecraft/world/entity/animal/Rabbit$EvilRabbitAttackGoal
accessible class net/minecraft/world/entity/animal/Rabbit$RabbitAvoidEntityGoal
accessible class net/minecraft/world/entity/animal/Rabbit$RabbitPanicGoal
accessible class net/minecraft/world/entity/animal/Rabbit$RaidGardenGoal
accessible class net/minecraft/world/entity/monster/Evoker$EvokerAttackSpellGoal
accessible class net/minecraft/world/entity/monster/Evoker$EvokerCastingSpellGoal
accessible class net/minecraft/world/entity/monster/Evoker$EvokerSummonSpellGoal
accessible class net/minecraft/world/entity/monster/Illusioner$IllusionerBlindnessSpellGoal
accessible class net/minecraft/world/entity/monster/Illusioner$IllusionerMirrorSpellGoal
accessible class net/minecraft/world/entity/monster/Vex$VexChargeAttackGoal
accessible class net/minecraft/world/entity/monster/Vex$VexCopyOwnerTargetGoal
accessible class net/minecraft/world/entity/monster/Vex$VexRandomMoveGoal
accessible class net/minecraft/world/entity/monster/Vindicator$VindicatorBreakDoorGoal
accessible class net/minecraft/world/entity/monster/Vindicator$VindicatorJohnnyAttackGoal
accessible class net/minecraft/world/entity/monster/Vindicator$VindicatorMeleeAttackGoal
accessible class net/minecraft/world/entity/raid/Raider$HoldGroundAttackGoal
accessible class net/minecraft/world/entity/raid/Raider$RaiderMoveThroughVillageGoal
accessible class net/minecraft/world/entity/monster/Ravager$RavagerMeleeAttackGoal
accessible class net/minecraft/world/entity/monster/Shulker$ShulkerAttackGoal
accessible class net/minecraft/world/entity/monster/Shulker$ShulkerDefenseAttackGoal
accessible class net/minecraft/world/entity/monster/Shulker$ShulkerNearestAttackGoal
accessible class net/minecraft/world/entity/monster/Shulker$ShulkerPeekGoal
accessible class net/minecraft/world/entity/monster/Silverfish$SilverfishMergeWithStoneGoal
accessible class net/minecraft/world/entity/monster/Silverfish$SilverfishWakeUpFriendsGoal
accessible class net/minecraft/world/entity/monster/Slime$SlimeAttackGoal
accessible class net/minecraft/world/entity/monster/Slime$SlimeFloatGoal
accessible class net/minecraft/world/entity/monster/Slime$SlimeKeepOnJumpingGoal
accessible class net/minecraft/world/entity/monster/Slime$SlimeRandomDirectionGoal
accessible class net/minecraft/world/entity/animal/Squid$SquidRandomMovementGoal
accessible class net/minecraft/world/entity/animal/Squid$SquidFleeGoal
accessible class net/minecraft/world/entity/monster/Spider$SpiderAttackGoal
accessible class net/minecraft/world/entity/monster/Spider$SpiderTargetGoal
accessible class net/minecraft/world/entity/monster/Strider$StriderGoToLavaGoal
accessible class net/minecraft/world/entity/animal/Turtle$TurtleBreedGoal
accessible class net/minecraft/world/entity/animal/Turtle$TurtleGoHomeGoal
accessible class net/minecraft/world/entity/animal/Turtle$TurtleGoToWaterGoal
accessible class net/minecraft/world/entity/animal/Turtle$TurtleLayEggGoal
accessible class net/minecraft/world/entity/animal/Turtle$TurtlePanicGoal
accessible class net/minecraft/world/entity/animal/Turtle$TurtleRandomStrollGoal
accessible class net/minecraft/world/entity/animal/Turtle$TurtleTravelGoal
accessible class net/minecraft/world/entity/animal/Wolf$WolfAvoidEntityGoal
accessible class net/minecraft/world/entity/animal/Wolf$WolfPanicGoal

accessible field net/minecraft/stats/Stat formatter Lnet/minecraft/stats/StatFormatter;

accessible field net/minecraft/world/level/levelgen/structure/structures/JigsawStructure startPool Lnet/minecraft/core/Holder;

accessible method net/minecraft/server/commands/GameRuleCommand setRule (Lcom/mojang/brigadier/context/CommandContext;Lnet/minecraft/world/level/GameRules$Key;)I
accessible method net/minecraft/server/commands/GameRuleCommand queryRule (Lnet/minecraft/commands/CommandSourceStack;Lnet/minecraft/world/level/GameRules$Key;)I

accessible field net/minecraft/world/level/block/DispenserBlock DISPENSER_REGISTRY Ljava/util/Map;