name: Build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
    - name: Caching
      uses: actions/cache@v2.1.7
      with:
        path: |
          ~/.brachyura/cache
          .brachyura
          buildscript/build
        key: ${{ runner.os }}-brachyura-${{ hashFiles('**/Buildscript.java') }}
        restore-keys: z${{ runner.os }}-brachyura
    - name: Build with Brachyura
      run: java -jar brachyura-bootstrap-0.jar build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs
