name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on:
      ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Cache Gradle configuration
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/settings.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish to GitHub
        uses: AButler/upload-release-assets@v2.0.2
        with:
          files: build/libs/*.jar
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Modrinth using Minotaur
        run: ./gradlew modrinth
