name: Publish

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3.5.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Caching
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle
            .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish to GitHub
        uses: AButler/upload-release-assets@v2.0.2
        with:
          files: |
            build/libs/*.jar
            repo-token = ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to Modrinth using Minotaur
        run: |
          echo "${{ github.event.release.body }}" > CHANGELOG.md
          ./gradlew modrinth
